dist: xenial

language: generic

env:
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
  - OCAML_VERSION=4.11

os:
  - freebsd
  - linux
  - osx

jobs:
  include:
  - os: linux
    env: OCAML_VERSION=4.11 INSTALL_LOCAL=1

cache:
  directories:
    - $HOME/.opam

addons:
  apt:
    packages:
      - autoconf
      - autotools-dev
      - libtool
      - pkg-config
      - libffi-dev
  homebrew:
    packages:
      - autoconf
      - automake
      - libtool
      - pkg-config
      - libffi
    
install:
  - test -e .travis-ocaml.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh

script:
  - opam pin -y -v -t add .
  - ls -l $(opam var libdash:lib)
  - cat $(opam var libdash:lib)/META
  - opam exec -- make -C test test
  - opam uninstall libdash # clear the cache

