os: linux
dist: xenial

language: generic

env:
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.09 INSTALL_LOCAL=1
  - OCAML_VERSION=4.11.0+trunk OCAML_BETA=enable
    
install:
  - sudo apt-get install -y autoconf autotools-dev libtool pkg-config libffi-dev
  - test -e .travis-ocaml.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh

script:
  - opam pin -y -t add .
  - (cd test; opam exec -- make test)

