dist: xenial

language: generic

cache:
  directories:
    - $HOME/.opam

matrix:
  include:
  - os: osx
    osx_image: xcode11.3
    env: OCAML_VERSION=4.09
  - os: freebsd
    env: OCAML_VERSION=4.09
  - os: linux
    env: OCAML_VERSION=4.09 INSTALL_LOCAL=1
  - os: linux
    env: OCAML_VERSION=4.11.0+trunk OCAML_BETA=enable
  allow_failures:
  - os: freebsd
    env: OCAML_VERSION=4.09
        
install:
  - which apt-get && sudo apt-get install -y autoconf autotools libtool pkg-config libffi-dev
  - which brew && brew install -y  autoconf automake libtool pkg-config libffi
  - test -e .travis-ocaml.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh

script:
  - opam pin -y -v -t add .
  - ls -l $(opam var libdash:lib)
  - LD_LIBRARY_PATH=$(opam var libdash:lib) opam exec -- make -C test test
  - opam uninstall libdash # clear the cache

